name: github_repo_viewer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_route: ^7.4.0
  collection: ^1.17.1
  dartz: ^0.10.1
  dio: ^5.2.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  http: ^0.13.0
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  oauth2: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod: ^2.3.6
  sembast: ^3.4.7
  webview_flutter: ^4.2.2
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.5
  lint: ^2.1.2
  auto_route_generator: ^7.1.1
  json_serializable: ^6.7.0
  
flutter:
  uses-material-design: true
